### ISSUE TITLE
No failure when I run this repo

### ISSUE THREAD

**Issue by vitch** [justinross/e-octane-bug#1]
I came across this repo when searching for an error we're getting when trying to update to latest ember:

> TypeError: 'ownKeys' on proxy: trap returned extra keys but proxy target is non-extensible

It seems like you had the same problem as us so I thought it would help but when I check out the repo and `yarn` and `ember s` both routes seem to work fine!

The good news is that when I `npm install`ed I could reproduce your error. So I guess it's been fixed in an in range upstream dependency - I'll investigate now to see where!

Sidenote: did you report this as a bug on ember or anywhere and if so do you have the URL?

**Comment by vitch** [comment]
Bumping `@glimmer/component` to `0.14.0-alpha.11` and re-running `npm install` fixed your example for me :)

Now to figure out why that didn't help in our case!

**Comment by justinross** [comment]
Hi! I reported it in the ember discord server (“reported” in this case was really more of a “asked for help”). 

The issue was fixed [here](https://github.com/glimmerjs/glimmer.js/pull/201) I believe, which was merged with glimmerjs master (0.14.0-alpha.10 I think). 😁

**Comment by vitch** [comment]
Thanks!

It looks like updating `@glimmer/component` to `0.14.0-alpha.11` *and* running the canary of `ember-source` you are running fixes it in our app. I'm not sure what it is about the `ember-source` canary but I'll ask over on that ticket...
